version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
